spring :
  datasource :
    url : jdbc:mysql://139.9.176.197:3306/db-it?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2b8
    username : root
    password : ENC(8imjgIFnmC4ekx3UC+mDseak5js9PX2g)
    driverClassName : com.mysql.jdbc.Driver
    platform: mysql
#    schema: classpath:/schema.sql
    #第一次启动做建表用，之后注释掉
#    initialization-mode: always
mybatis :
  config-location : classpath:mapper/*/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# JWT
jwt:
  header: Authorization
  secret: secret
  #token有效期一天
  expiration: 86400
  tokenHead: "Bearer "

jasypt:
  encryptor:
    password: 5AF6814C150D71E4D9A2FA5D26C0F667